### ISSUE TITLE
Monitor Dimensions in dmenu_custom no longer supported?

### ISSUE THREAD

**Issue by ejwmoreau** [scottgreenup/desktop#3]
Location: https://github.com/scottgreenup/desktop/blob/master/bin/dmenu_custom#L59

It seems like dmenu has stopped supporting monitor dimensions (x, y, h, w) and instead they have a '-m monitor' option, where monitor is usually 0.
Might need to account for when multiple displays are present and which one is selected, etc.

**Comment by scottgreenup** [comment]
Are you using dmenu or dmenu2?

**Comment by ejwmoreau** [comment]
Hmm, I'm actually not sure, since it was on a bootable USB. I'm guessing it doesn't work with dmenu but works with dmenu2?

**Comment by scottgreenup** [comment]
Yeah, it works with dmenu2 -- Double check when you can :) Dmenu2 is in the AUR -- https://aur.archlinux.org/packages/dmenu2/

**Comment by ejwmoreau** [comment]
Just checked and yeah, I was using dmenu :stuck_out_tongue: 
Mystery solved!
