### ISSUE TITLE
Keychain timeout

### ISSUE THREAD

**Issue by ejwmoreau** [scottgreenup/desktop#7]
Your keychain aliases have timeouts of 300 and 3600 in ~/.bashrc, which are intended to be in seconds:
https://github.com/scottgreenup/desktop/blob/master/home/bashrc#L168

However, keychain's man page says that the timeout is represented in minutes. So your aliases actually timeout at 5 hours and 2.5 days :smile:

**Comment by ejwmoreau** [comment]
@scottgreenup Just in case it doesn't ping you

**Comment by scottgreenup** [comment]
Thank you for the heads up. Fixed in ea60201b496535c54da1a5383159d617701dcada.
